name: sign_in_with_apple_server
description: Server-side utilities for Sign in with Apple.
version: 0.2.0
repository: https://github.com/LunaONE/sign_in_with_apple_server

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  dart_jsonwebtoken: ^3.1.0
  http: ">=1.1.0 <2.0.0"
  meta: ^1.11.0

dev_dependencies:
  clock: ^1.1.1
  lints: ^4.0.0
  test: ^1.24.0
