publish_to: none

name: sign_in_with_apple_server_relic_example
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/LunaONE/sign_in_with_apple_server

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  relic: ^0.4.0
  sign_in_with_apple_server: ^1.0.0
  sign_in_with_apple_server_relic: ^1.0.0

dev_dependencies:
  lints: ">=3.0.0 <7.0.0"
  test: ^1.24.0

dependency_overrides:
  sign_in_with_apple_server:
    path: ../../sign_in_with_apple_server
  sign_in_with_apple_server_relic:
    path: ../
